apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-web
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:eu-north-1:143985718263:certificate/0017bb5b-5925-4364-9d18-28db05e1750c"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
spec:
  selector:
    app: {{ .Release.Name }}-web
  ports:
    - name: http
      port: 80
      targetPort: {{ .Values.frontend.port }}
    - name: https
      port: 443
      targetPort: {{ .Values.frontend.port }}
  type: {{ .Values.service.frontendType }}