global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'trump-card'
    static_configs:
      - targets: ['13.50.114.92:3001']
    metrics_path: '/api/metrics'

  - job_name: 'node'
    static_configs:
      - targets: ['13.50.114.92:9100']