apiVersion: v1
kind: Service
metadata:
  name: trump-card-web
  namespace: default
spec:
  selector:
    app: trump-card-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort


  